/**
 * Gate fixture: a legal `definePlugin` sample for protocol smoke tests.
 * Package is `vmz-fixtures` (no `plugin` in the package/dir name).
 */

import { contentHash, definePlugin } from '@vmz/plugin';

const NOTE = `<!-- generated by vmz-fixtures; not a component -->\n`;

export default definePlugin({
    name: 'protocol-fixture',
    version: '0.1.0',
    protocol: '0.1.0',
    stages: ['workspace_resolve', 'analyzer', 'target'],
    deterministic: true,
    async contribute(ctx) {
        if (ctx.stage === 'workspace_resolve') {
            const content = NOTE;
            return {
                stage: 'workspace_resolve',
                cacheKey: 'fixture:note',
                items: [
                    {
                        id: 'fixture-note',
                        kind: 'source',
                        path: 'src/.vmz-fixture-note.txt',
                        content,
                        contentHash: contentHash(content),
                        materialize: true,
                    },
                ],
            };
        }
        if (ctx.stage === 'analyzer') {
            return {
                stage: 'analyzer',
                cacheKey: 'fixture:analyzer',
                items: [
                    {
                        id: 'fixture-advice',
                        kind: 'analyzer',
                        path: 'src/Application.vmz',
                        severity: 'advice',
                        message: 'protocol fixture online',
                        code: 'vmz.fixture.protocol',
                    },
                ],
            };
        }
        if (ctx.stage === 'target') {
            return {
                stage: 'target',
                cacheKey: 'fixture:target',
                items: [
                    {
                        id: 'edge-preview',
                        kind: 'target',
                        targetId: 'edge-preview',
                        targetKind: 'edge',
                        manifest: {
                            runtime: 'edge',
                            routes: ['/'],
                            note: 'fixture deployment target — does not redefine program meaning',
                        },
                    },
                ],
            };
        }
        return { stage: ctx.stage, items: [] };
    },
});
