//! Lang CodeGenerator (Rust server glue).

use vmz_types::ComponentDecl;

/// Emit rustc-facing glue for one server unit + JSON capability table.
pub fn emit_rust_server_unit(
    module_id: &str,
    decl: &ComponentDecl,
    dsl_source: &str,
) -> (String, String) {
    let type_name = &decl.name;
    let mut caps = String::new();
    for m in &decl.methods {
        if m.is_private || m.name == "constructor" {
            continue;
        }
        caps.push_str(&format!(
            "    Capability {{ name: {:?}, async_: {} }},\n",
            m.name, m.is_async
        ));
    }

    let rs = format!(
        r#"//! @generated by vmz-generator from `{module_id}` - rust-flavor Server DSL (do not edit by hand)
#![allow(unused_imports)]

{dsl_source}

/// Language-neutral capability descriptors for this server unit.
pub struct Capability {{
    pub name: &'static str,
    pub async_: bool,
}}

pub const CAPABILITIES: &[Capability] = &[
{caps}];

pub type ServerType = {type_name};
"#
    );

    let table = serde_json::json!({
        "schema": "vmz.server.capability_table.v0",
        "moduleId": module_id,
        "lang": "rust",
        "className": type_name,
        "capabilities": decl
            .methods
            .iter()
            .filter(|m| !m.is_private && m.name != "constructor")
            .map(|m| {
                serde_json::json!({
                    "name": m.name,
                    "async": m.is_async,
                })
            })
            .collect::<Vec<_>>(),
    });

    (rs, crate::to_pretty_json(&table).unwrap_or_else(|_| "{}".into()))
}
