//! Serve / static host entry modules (JsCodeGenerator).

use std::collections::BTreeMap;

use super::ast_util::{js_string_literal, oxc_reprint_module};
use super::emit::EmittedJs;

/// Component entry descriptor for [`emit_serve_entry_client`].
#[derive(Debug, Clone)]
pub struct EntryComponent {
    /// Export / register name.
    pub name: String,
    /// Relative module path without leading `./` (e.g. `components/Foo.client.js`).
    pub entry: String,
}

/// Full serve-host `entry-client.js` (hydrateRoute + client nav).
pub fn emit_serve_entry_client(
    eager: &[EntryComponent],
    lazy: &[EntryComponent],
    cache_query: &str,
) -> EmittedJs {
    let q = if cache_query.is_empty() {
        String::new()
    } else if cache_query.starts_with('?') {
        cache_query.to_string()
    } else {
        format!("?{cache_query}")
    };
    let mut imports = String::new();
    for e in eager {
        let spec = js_string_literal(&format!("./{}{}", e.entry, q));
        imports.push_str(&format!("import {} from {spec};\n", e.name));
    }
    let map = if eager.is_empty() {
        String::new()
    } else {
        format!(
            "registerComponents({{ {} }});",
            eager.iter().map(|e| e.name.as_str()).collect::<Vec<_>>().join(", ")
        )
    };
    let mut entry_by_name = BTreeMap::new();
    for e in eager.iter().chain(lazy.iter()) {
        entry_by_name.insert(e.name.clone(), e.entry.clone());
    }
    let entry_json = crate::to_json(&entry_by_name).unwrap_or_else(|_| "{}".into());
    let loader = if lazy.is_empty() {
        String::new()
    } else {
        format!(
            r#"const __vmzComponentEntries = {entry_json};
globalThis.__vmzLoadComponent = async (name) => {{
  const entry = __vmzComponentEntries[name] || ("components/" + name + ".client.js");
  const mod = await import("./" + entry + "{q}");
  return mod.default;
}};"#
        )
    };
    let dom = js_string_literal(&format!("./vmz-dom.js{q}"));
    let nav = js_string_literal(&format!("./vmz-client-nav.js{q}"));
    let code = format!(
        r#"/**
 * Generated by vmz-generator - hydrate matched file-route page (data-vmz-page) + layout chain + client Link takeover.
 */
import {{ registerComponents, hydrate, hydrateRoute, hydrateRoutePage, destroy }} from {dom};
import {{ installClientNavigation }} from {nav};
{imports}
{map}
{loader}
const root = document.getElementById("app");
if (!root) throw new Error("vmz: missing #app");
const chunkId = root.getAttribute("data-vmz-page");
if (!chunkId) throw new Error("vmz: missing data-vmz-page");
let props = {{}};
try {{
  const raw = root.getAttribute("data-vmz-props");
  if (raw) props = JSON.parse(raw);
}} catch {{ /* ignore */ }}
const layoutChain = (root.getAttribute("data-vmz-layout") || "").split(",").map((s) => s.trim()).filter(Boolean);
const layoutCtors = [];
for (const id of layoutChain) {{
  layoutCtors.push((await import("./" + id + ".client.js{q}")).default);
}}
const Page = (await import("./" + chunkId + ".client.js{q}")).default;
await hydrateRoute(Page, root, props, layoutCtors);
installClientNavigation({{
  hydrate,
  hydrateRoute,
  hydrateRoutePage,
  destroy,
  importPage: async (id) => (await import("./" + id + ".client.js{q}")).default,
}});
"#
    );
    let code = oxc_reprint_module(&code).unwrap_or(code);
    EmittedJs { code, map: None }
}

/// EventEntry zero-framework bootstrap shell (island resume on first event).
pub fn emit_serve_entry_event(cache_query: &str) -> EmittedJs {
    let q = if cache_query.is_empty() {
        String::new()
    } else if cache_query.starts_with('?') {
        cache_query.to_string()
    } else {
        format!("?{cache_query}")
    };
    let dom = js_string_literal(&format!("./vmz-dom.js{q}"));
    let code = format!(
        r#"/**
 * Generated by vmz-generator - EventEntry zero-framework JS shell.
 */
(async () => {{
  const roots = [...document.querySelectorAll(
    '[data-vmz-entry="event"], [data-vmz-client="event"], [data-vmz-client^="event:"]',
  )];
  for (const el of roots) {{
    if (el.__vmzEventWired) continue;
    el.__vmzEventWired = true;
    const strat = el.getAttribute("data-vmz-client") || "event";
    let type = "click";
    if (strat.startsWith("event:") && strat.length > 6) type = strat.slice(6) || "click";
    else if (strat === "click") type = "click";
    el.addEventListener(
      type,
      async () => {{
        const {{ registerComponents, resume }} = await import({dom});
        const name = el.getAttribute("data-vmz-island");
        if (!name) throw new Error("vmz: EventEntry missing data-vmz-island");
        const Comp = (await import("./components/" + name + ".client.js{q}")).default;
        registerComponents({{ [name]: Comp }});
        await resume(Comp, el);
      }},
      {{ once: true }},
    );
  }}
}})();
"#
    );
    let code = oxc_reprint_module(&code).unwrap_or(code);
    EmittedJs { code, map: None }
}
