//! Locale runtime modules (`dist/locales/*.js`).

use super::ast_util::oxc_reprint_module;
use super::emit::EmittedJs;

/// One exported message function in a locale module.
#[derive(Debug, Clone)]
pub struct LocaleExport {
    /// JS export name (must be a valid identifier).
    pub export_name: String,
    /// Locale id -> template string.
    pub variants: Vec<(String, String)>,
    /// When true, emit `(args)` parameter.
    pub has_params: bool,
}

/// Emit one `dist/locales/{catalogId}.js` module.
pub fn emit_locale_runtime_module(default_locale: &str, exports: &[LocaleExport]) -> EmittedJs {
    let default_lit = serde_json::to_string(default_locale).unwrap_or_else(|_| "\"en\"".into());
    let mut lines = vec![
        "/**".into(),
        " * Generated by vmz-generator - locale runtime module.".into(),
        " */".into(),
        format!("const __vmzDefaultLocale = {default_lit};"),
        "function __vmzLocaleId() {".into(),
        "  if (typeof globalThis !== \"undefined\" && globalThis.__vmzLocaleIdHint) {".into(),
        "    return String(globalThis.__vmzLocaleIdHint);".into(),
        "  }".into(),
        "  if (typeof document !== \"undefined\") {".into(),
        "    const d = document.documentElement?.getAttribute(\"data-locale\");".into(),
        "    if (d) return d;".into(),
        "    const lang = document.documentElement?.lang;".into(),
        "    if (lang === \"en\" || lang === \"en-US\" || lang === \"en-us\") return \"en-us\";".into(),
        "    if (lang === \"zh\" || lang === \"zh-CN\" || lang === \"zh-Hans\" || lang === \"zh-hans\") return \"zh-hans\";".into(),
        "  }".into(),
        "  try {".into(),
        "    const stored = localStorage.getItem(\"vmz.locale\");".into(),
        "    if (stored) return stored;".into(),
        "  } catch {}".into(),
        "  return __vmzDefaultLocale;".into(),
        "}".into(),
        "function __vmzFormat(template, args) {".into(),
        "  if (!args) return String(template ?? \"\");".into(),
        "  return String(template ?? \"\").replace(/\\{(\\w+)(?:,\\s*\\w+)?\\}/g, (m, name) =>".into(),
        "    Object.prototype.hasOwnProperty.call(args, name) ? String(args[name]) : m".into(),
        "  );".into(),
        "}".into(),
        "function __vmzPick(variants, args) {".into(),
        "  const id = __vmzLocaleId();".into(),
        "  const template = variants[id] ?? variants[__vmzDefaultLocale] ?? \"\";".into(),
        "  return __vmzFormat(template, args);".into(),
        "}".into(),
        String::new(),
    ];

    for exp in exports {
        let mut map = serde_json::Map::new();
        for (loc, template) in &exp.variants {
            map.insert(loc.clone(), serde_json::Value::String(template.clone()));
        }
        let lit = serde_json::Value::Object(map).to_string();
        if exp.has_params {
            lines.push(format!(
                "export function {}(args) {{ return __vmzPick({lit}, args); }}",
                exp.export_name
            ));
        } else {
            lines.push(format!(
                "export function {}() {{ return __vmzPick({lit}); }}",
                exp.export_name
            ));
        }
    }
    lines.push(String::new());
    let raw = lines.join("\n");
    let code = oxc_reprint_module(&raw).unwrap_or(raw);
    EmittedJs { code, map: None }
}
