//! Locale runtime modules (`dist/locales/*.js`).

use super::ast_util::oxc_reprint_module_required;
use super::emit::EmittedJs;

/// One exported message function in a locale module.
#[derive(Debug, Clone)]
pub struct LocaleExport {
    /// JS export name (must be a valid identifier).
    pub export_name: String,
    /// Locale id -> template string.
    pub variants: Vec<(String, String)>,
    /// When true, emit `(args)` parameter.
    pub has_params: bool,
}

/// Emit one `dist/locales/{catalogId}.js` module.
pub fn emit_locale_runtime_module(default_locale: &str, exports: &[LocaleExport]) -> EmittedJs {
    let default_lit = serde_json::to_string(default_locale).unwrap_or_else(|_| "\"en\"".into());
    let mut lines = vec![
        "/**".into(),
        " * Generated by vmz-generator - locale runtime module.".into(),
        " */".into(),
        format!("const __vmzDefaultLocale = {default_lit};"),
        "function __vmzLocaleId() {".into(),
        "  if (typeof globalThis !== \"undefined\" && globalThis.__vmzLocaleIdHint) {".into(),
        "    return String(globalThis.__vmzLocaleIdHint);".into(),
        "  }".into(),
        "  if (typeof document !== \"undefined\") {".into(),
        "    const d = document.documentElement?.getAttribute(\"data-locale\");".into(),
        "    if (d) return d;".into(),
        "    const lang = document.documentElement?.lang;".into(),
        "    if (lang === \"en\" || lang === \"en-US\" || lang === \"en-us\") return \"en-us\";".into(),
        "    if (lang === \"zh\" || lang === \"zh-CN\" || lang === \"zh-Hans\" || lang === \"zh-hans\") return \"zh-hans\";".into(),
        "  }".into(),
        "  try {".into(),
        "    const stored = localStorage.getItem(\"vmz.locale\");".into(),
        "    if (stored) return stored;".into(),
        "  } catch {}".into(),
        "  return __vmzDefaultLocale;".into(),
        "}".into(),
        "function __vmzFormat(template, args) {".into(),
        "  if (!args) return String(template ?? \"\");".into(),
        "  return String(template ?? \"\").replace(/\\{(\\w+)(?:,\\s*\\w+)?\\}/g, (m, name) =>".into(),
        "    Object.prototype.hasOwnProperty.call(args, name) ? String(args[name]) : m".into(),
        "  );".into(),
        "}".into(),
        "function __vmzPick(variants, args) {".into(),
        "  const id = __vmzLocaleId();".into(),
        "  const template = variants[id] ?? variants[__vmzDefaultLocale] ?? \"\";".into(),
        "  return __vmzFormat(template, args);".into(),
        "}".into(),
        String::new(),
    ];

    for exp in exports {
        let mut map = serde_json::Map::new();
        for (loc, template) in &exp.variants {
            map.insert(loc.clone(), serde_json::Value::String(template.clone()));
        }
        let lit = serde_json::Value::Object(map).to_string();
        if exp.has_params {
            lines.push(format!(
                "export function {}(args) {{ return __vmzPick({lit}, args); }}",
                exp.export_name
            ));
        } else {
            lines.push(format!(
                "export function {}() {{ return __vmzPick({lit}); }}",
                exp.export_name
            ));
        }
    }
    lines.push(String::new());
    let raw = lines.join("\n");
    let code = oxc_reprint_module_required(&raw, "locale runtime module");
    EmittedJs { code, map: None }
}

/// One typed-module parameter for [`emit_locale_typed_module`].
#[derive(Debug, Clone)]
pub struct LocaleTypedParam {
    /// Parameter name.
    pub name: String,
    /// `plural` / `number` -> `number`; otherwise `string`.
    pub kind: String,
}

/// One `export declare function` in a locale `.d.ts` stub.
#[derive(Debug, Clone)]
pub struct LocaleTypedExport {
    /// Export function name.
    pub export_name: String,
    /// ICU / message params (empty => zero-arg).
    pub params: Vec<LocaleTypedParam>,
}

/// Emit `#locales/{catalog}.d.ts` stub text (`vmz.locale.typed_module.v0`).
pub fn emit_locale_typed_module(module_label: &str, exports: &[LocaleTypedExport]) -> String {
    let mut lines = vec![
        format!("/** Generated LocalizedText module - {module_label} (vmz.locale.typed_module.v0) */"),
        "export type LocalizedText = string & { readonly __brand: 'LocalizedText' };".into(),
        String::new(),
    ];
    for exp in exports {
        if exp.params.is_empty() {
            lines.push(format!(
                "export declare function {}(): LocalizedText;",
                exp.export_name
            ));
        } else {
            let args: Vec<String> = exp
                .params
                .iter()
                .map(|p| {
                    let ty = if p.kind == "plural" || p.kind == "number" {
                        "number"
                    } else {
                        "string"
                    };
                    format!("{}: {ty}", p.name)
                })
                .collect();
            lines.push(format!(
                "export declare function {}(args: {{ {} }}): LocalizedText;",
                exp.export_name,
                args.join("; ")
            ));
        }
    }
    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typed_module_emits_params() {
        let text = emit_locale_typed_module(
            "#locales/ui",
            &[
                LocaleTypedExport { export_name: "hello".into(), params: vec![] },
                LocaleTypedExport {
                    export_name: "count".into(),
                    params: vec![LocaleTypedParam { name: "n".into(), kind: "plural".into() }],
                },
            ],
        );
        assert!(text.contains("export declare function hello(): LocalizedText;"));
        assert!(text.contains("export declare function count(args: { n: number }): LocalizedText;"));
    }
}
