/**
 * rust-embedded packaging adapter: resource index + baseline closure.
 * Packaging only — does not invent route / MIME / fallback semantics.
 */
// @ts-nocheck

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { writePrettyJsonFile } from './pretty-json.js';

export const EMBEDDED_RESOURCE_INDEX_SCHEMA = 'vmz.embedded.resource_index.v0';

/** Paths that must never enter the embedded baseline closure. */
const SKIP_NAMES = new Set(['vmz-serve-host.mjs', 'vmz-serve-host.js', 'node_modules', '.git']);

/**
 * Walk outDir and build path → digest → relative blob path map.
 * Copies files into `dist/_vmz/embedded-baseline/` (whole release, no file-level mix).
 * @param {string} outDir
 * @param {{ siteId?: string, contractDigest?: string | null }} [opts]
 */
export function emitEmbeddedPackaging(outDir, opts = {}) {
    const vmzDir = path.join(outDir, '_vmz');
    const baselineDir = path.join(vmzDir, 'embedded-baseline');
    fs.mkdirSync(baselineDir, { recursive: true });

    /** @type {Array<{ path: string, digest: string, blob: string, bytes: number }>} */
    const objects = [];
    const root = path.resolve(outDir);

    walkFiles(root, (abs) => {
        const rel = toPosix(path.relative(root, abs));
        if (!rel || rel.startsWith('_vmz/embedded-baseline')) return;
        if (rel.startsWith('_vmz/embedded-resource-index')) return;
        const base = path.basename(abs);
        if (SKIP_NAMES.has(base)) return;
        // Keep other _vmz manifests inside baseline (contract, capability table, etc.)
        const buf = fs.readFileSync(abs);
        const digest = sha256Hex(buf);
        const blobRel = `objects/${digest.slice(0, 2)}/${digest}`;
        const blobAbs = path.join(baselineDir, blobRel);
        fs.mkdirSync(path.dirname(blobAbs), { recursive: true });
        if (!fs.existsSync(blobAbs)) fs.writeFileSync(blobAbs, buf);
        // Also mirror tree under baseline/tree for host convenience
        const treeAbs = path.join(baselineDir, 'tree', rel);
        fs.mkdirSync(path.dirname(treeAbs), { recursive: true });
        fs.copyFileSync(abs, treeAbs);
        objects.push({ path: rel, digest, blob: blobRel, bytes: buf.length });
    });

    objects.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
    const index = {
        schema: EMBEDDED_RESOURCE_INDEX_SCHEMA,
        siteId: opts.siteId || null,
        contractDigest: opts.contractDigest || null,
        objectCount: objects.length,
        objects,
    };
    index.indexDigest = sha256Hex(canonicalJson({ ...index, indexDigest: undefined }));

    const indexPath = path.join(vmzDir, 'embedded-resource-index.json');
    writePrettyJsonFile(indexPath, index);

    // Optional include_bytes entry point for Rust packaging adapters
    const rsPath = path.join(vmzDir, 'embedded_site.rs');
    fs.writeFileSync(
        rsPath,
        `// @generated by vmz — rust-embedded packaging adapter (do not edit)
// Index digest: ${index.indexDigest}
pub const EMBEDDED_RESOURCE_INDEX: &str = include_str!("embedded-resource-index.json");
`,
        'utf8',
    );

    return { index, indexPath, baselineDir };
}

/**
 * @param {string} dir
 * @param {(abs: string) => void} onFile
 */
function walkFiles(dir, onFile) {
    if (!fs.existsSync(dir)) return;
    for (const name of fs.readdirSync(dir)) {
        if (SKIP_NAMES.has(name)) continue;
        const abs = path.join(dir, name);
        const st = fs.statSync(abs);
        if (st.isDirectory()) {
            if (name === 'embedded-baseline' && path.basename(path.dirname(abs)) === '_vmz') continue;
            walkFiles(abs, onFile);
        } else if (st.isFile()) {
            onFile(abs);
        }
    }
}

function toPosix(p) {
    return p.split(path.sep).join('/');
}

function sha256Hex(data) {
    return crypto.createHash('sha256').update(data).digest('hex');
}

function canonicalJson(value) {
    return JSON.stringify(sortKeys(value));
}

function sortKeys(value) {
    if (Array.isArray(value)) return value.map(sortKeys);
    if (value && typeof value === 'object') {
        const out = {};
        for (const k of Object.keys(value).sort()) out[k] = sortKeys(value[k]);
        return out;
    }
    return value;
}
