/**
 * Conformance plugin for — proves structured contributions without VPG mutation.
 *
 * Stages: workspace_resolve (optional virtual note file), analyzer advice, target manifest.
 */

import { contentHash, definePlugin } from '@vmz/plugin';

const NOTE = `<!-- generated by vmz-plugin-conformance; not a component -->\n`;

export default definePlugin({
    name: 'vmz-plugin-conformance',
    version: '0.1.0',
    protocol: '0.1.0',
    stages: ['workspace_resolve', 'analyzer', 'target'],
    deterministic: true,
    async contribute(ctx) {
        if (ctx.stage === 'workspace_resolve') {
            // Non-vmz sidecar proving SourceContribution materialize + hash check.
            // (Does not invent component semantics — just a provenance-bearing file.)
            const content = NOTE;
            return {
                stage: 'workspace_resolve',
                cacheKey: 'conformance:note',
                items: [
                    {
                        id: 'conformance-note',
                        kind: 'source',
                        path: 'src/.vmz-conformance-note.txt',
                        content,
                        contentHash: contentHash(content),
                        materialize: true,
                    },
                ],
            };
        }
        if (ctx.stage === 'analyzer') {
            return {
                stage: 'analyzer',
                cacheKey: 'conformance:analyzer',
                items: [
                    {
                        id: 'conformance-advice',
                        kind: 'analyzer',
                        path: 'src/Application.vmz',
                        severity: 'advice',
                        message: 'conformance plugin online (N3)',
                        code: 'vmz.plugin.conformance',
                    },
                ],
            };
        }
        if (ctx.stage === 'target') {
            return {
                stage: 'target',
                cacheKey: 'conformance:target',
                items: [
                    {
                        id: 'edge-preview',
                        kind: 'target',
                        targetId: 'edge-preview',
                        targetKind: 'edge',
                        manifest: {
                            runtime: 'edge',
                            routes: ['/'],
                            note: 'conformance deployment target — does not redefine program meaning',
                        },
                    },
                ],
            };
        }
        return { stage: ctx.stage, items: [] };
    },
});
